import os
import json
import logging
import requests
from typing import List, Dict, Any, Optional
from ml_worker.config import WorkerConfig

logger = logging.getLogger("ml_worker.llm_diarizer")

class LLMRealignmentEngine:
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY", "")
        self.model = os.getenv("OPENAI_MODEL", "gpt-4o")
        self.enabled = os.getenv("ENABLE_LLM_DIARIZATION", "true").lower() in ("true", "1", "yes")

    def process(self, segments: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Runs Layer 3 LLM Post-Processing on segments:
        1. Fixes acoustic legal homophone errors ("six d" -> "Order 8 Rule 6(d)", "call pleases" -> "As the Court pleases").
        2. Re-aligns speaker turn boundaries based on natural courtroom turn-taking and dialogue flow.
        """
        if not self.enabled or not self.api_key:
            logger.info("LLM Realignment disabled or OPENAI_API_KEY not configured. Skipping Layer 3 pass.")
            return segments

        if not segments:
            return segments

        try:
            logger.info(f"Running Layer 3 LLM Realignment pass on {len(segments)} segments using {self.model}...")

            # Prepare simplified input payload for LLM
            simplified_input = []
            for seg in segments:
                simplified_input.append({
                    "speaker": seg.get("speaker", "SPEAKER_00"),
                    "text": seg.get("text", "").strip(),
                    "start": seg.get("start"),
                    "end": seg.get("end")
                })

            # Extract set of original allowed speakers
            existing_speakers = sorted(list(set(seg.get("speaker", "SPEAKER_00") for seg in segments)))
            speaker_str = ", ".join(existing_speakers)

            prompt_system = (
                "You are an expert Courtroom Stenographer AI. You receive a raw transcript generated by acoustic speech models.\n"
                "Acoustic speech models often fragment sentences across segment boundaries, mishear legal citations, and over-segment speaker tags.\n\n"
                f"ALLOWED SPEAKER TAGS: [{speaker_str}]\n\n"
                "YOUR CORE RESPONSIBILITIES:\n"
                "1. CROSS-SEGMENT LEGAL TEXT & CITATION CORRECTION:\n"
                "   - Fix acoustic homophones and misheard legal phrasing across whole sentences (even if split across neighboring segments):\n"
                "     * 'six d' / 'six D' / 'rule six d' -> '6(d)' / 'Rule 6(d)'\n"
                "     * 'order eight rule' + 'six d' -> 'Order 8 Rule 6(d)'\n"
                "     * 'call pleases' / 'call places' / 'as you call pleases' -> 'As the Court pleases'\n"
                "     * 'frontiered' / 'front-ended' -> 'front-loaded'\n"
                "     * 'emotional notice' / 'motion and notice' -> 'Motion on Notice'\n"
                "     * 'right of summons' -> 'Writ of Summons'\n"
                "     * 'my lord' -> 'My Lord', 'your honor' -> 'Your Honor', 'justice seydoux' -> 'Justice Saidu'\n"
                "   - Format Case & Suit Numbers cleanly: Convert spelled-out words, digits, and misheard court codes into standard suit citations (e.g., 'Suits number FAC/HEALTH/ONE nine zero FOUR/TWENTY nineteen' -> 'Suit No. FAC/L/1904/2019' or 'Suit No. FHC/L/1904/2019').\n"
                "2. CONSOLIDATE OVER-SEGMENTED SPEAKERS (MERGE TO TRUE HUMAN COUNT):\n"
                "   - Courtroom audio typically has ONLY 2 REAL HUMAN PARTICIPANTS (e.g. Counsel addressing the Judge, and the Judge presiding).\n"
                "   - Acoustic models over-segment a single person into multiple tags (e.g. SPEAKER_00 and SPEAKER_01 for the same Counsel addressing 'My Lord').\n"
                "   - Analyze dialogue honorifics ('My Lord', 'Your Honor', 'Sir?'), questions vs answers.\n"
                "   - Consolidate all turns uttered by the same human into a SINGLE speaker tag (e.g. SPEAKER_00 for Counsel, SPEAKER_01 for the Judge).\n"
                "   - DO NOT create or invent any extra speaker tags (such as SPEAKER_03). Use ONLY the minimum necessary allowed tags (e.g. SPEAKER_00 and SPEAKER_01).\n"
                "3. MERGE CONTINUOUS SENTENCES & FIX TIMINGS:\n"
                "   - Feel free to merge continuous segments belonging to the same sentence/speaker turn to form clean, natural paragraphs.\n"
                "   - Use the 'start' timestamp of the first merged segment and 'end' timestamp of the last merged segment.\n\n"
                "Return ONLY a valid JSON object with a single top-level key 'realigned_segments':\n"
                "{\n"
                "  \"realigned_segments\": [\n"
                "    { \"speaker\": \"SPEAKER_00\", \"text\": \"My Lord is giving me a new name.\", \"start\": 0.0, \"end\": 3.72 },\n"
                "    { \"speaker\": \"SPEAKER_01\", \"text\": \"Well, choose the one you want.\", \"start\": 5.38, \"end\": 7.18 }\n"
                "  ]\n"
                "}"
            )

            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }

            body = {
                "model": self.model,
                "response_format": {"type": "json_object"},
                "temperature": 0.1,
                "messages": [
                    {"role": "system", "content": prompt_system},
                    {"role": "user", "content": json.dumps({"raw_segments": simplified_input})}
                ]
            }

            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=body,
                timeout=60
            )

            if response.status_code != 200:
                logger.error(f"OpenAI API call failed with status {response.status_code}: {response.text}")
                return segments

            result_json = response.json()
            content = result_json["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            realigned_segments = parsed.get("realigned_segments", [])

            if not realigned_segments:
                logger.warning("LLM returned empty realigned segments. Using original segments.")
                return segments

            logger.info(f"LLM Realignment pass completed: returned {len(realigned_segments)} realigned segments.")

            # Map realigned text and speaker tags back into segment structures with strict speaker tag enforcement
            final_segments = []
            allowed_set = set(existing_speakers)
            last_valid_speaker = existing_speakers[0] if existing_speakers else "SPEAKER_00"

            for seg in realigned_segments:
                spk = seg.get("speaker", "SPEAKER_00")
                if spk not in allowed_set:
                    logger.warning(f"LLM returned unauthorized speaker tag '{spk}' (allowed: {allowed_set}). Remapping to '{last_valid_speaker}'.")
                    spk = last_valid_speaker
                else:
                    last_valid_speaker = spk

                txt = seg.get("text", "")
                st = seg.get("start", 0.0)
                et = seg.get("end", 0.0)

                # Split words
                raw_words = txt.split()
                duration = max(0.1, et - st)
                step = duration / max(1, len(raw_words))

                words_list = []
                for idx, w_txt in enumerate(raw_words):
                    words_list.append({
                        "word": w_txt,
                        "start": round(st + (idx * step), 3),
                        "end": round(st + ((idx + 1) * step), 3),
                        "speaker": spk
                    })

                final_segments.append({
                    "start": st,
                    "end": et,
                    "text": txt,
                    "speaker": spk,
                    "words": words_list
                })

            return final_segments

        except Exception as e:
            logger.error(f"Error during LLM Realignment pass: {e}")
            return segments
