import os
import json
import logging
import requests
from typing import List, Dict, Any, Optional
from ml_worker.config import WorkerConfig

logger = logging.getLogger("ml_worker.llm_diarizer")

class LLMRealignmentEngine:
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY", "")
        self.model = os.getenv("OPENAI_MODEL", "gpt-4o")
        self.enabled = os.getenv("ENABLE_LLM_DIARIZATION", "true").lower() in ("true", "1", "yes")

    def process(self, segments: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Runs Layer 3 LLM Post-Processing on segments:
        1. Fixes acoustic legal homophone errors ("six d" -> "Order 8 Rule 6(d)", "call pleases" -> "As the Court pleases").
        2. Re-aligns speaker turn boundaries based on natural courtroom turn-taking and dialogue flow.
        """
        if not self.enabled or not self.api_key:
            logger.info("LLM Realignment disabled or OPENAI_API_KEY not configured. Skipping Layer 3 pass.")
            return segments

        if not segments:
            return segments

        try:
            logger.info(f"Running Layer 3 LLM Realignment pass on {len(segments)} segments using {self.model}...")

            # Prepare simplified input payload for LLM
            simplified_input = []
            for seg in segments:
                simplified_input.append({
                    "speaker": seg.get("speaker", "SPEAKER_00"),
                    "text": seg.get("text", "").strip(),
                    "start": seg.get("start"),
                    "end": seg.get("end")
                })

            # Extract set of original allowed speakers
            existing_speakers = sorted(list(set(seg.get("speaker", "SPEAKER_00") for seg in segments)))
            speaker_str = ", ".join(existing_speakers)

            prompt_system = (
                "You are an expert Courtroom Stenographer AI. You receive a raw transcript generated by acoustic speech models.\n"
                "In courtroom audio, speakers rapidly exchange single-sentence remarks (e.g. Questions from the Judge, Answers from Counsel, Interjections).\n"
                "Acoustic models often group multiple speaker turns into a single speaker bank, or mistake legal phrasing and suit numbers.\n\n"
                f"ALLOWED SPEAKER TAGS: [{speaker_str}]\n\n"
                "Your task:\n"
                "1. Correct acoustic homophone errors, legal terminology, and case/suit numbers:\n"
                "   - 'six d' -> '6(d)'\n"
                "   - 'call pleases' -> 'Court pleases'\n"
                "   - 'frontiered' -> 'front-loaded'\n"
                "   - 'emotional notice' -> 'Motion on Notice'\n"
                "   - Suit/Case Numbers: Format suit numbers with standard forward slashes, upper-case letter codes, and numeric years (e.g., 'Suits number FAC/HEALTH/ONE nine zero FOUR/TWENTY nineteen' -> 'Suit No. FAC/L/1904/2019'). Convert spelled-out words in suit numbers ('ONE nine zero FOUR' -> '1904', 'TWENTY nineteen' -> '2019', 'HEALTH' -> 'L').\n"
                "2. Re-align speaker tags based on legal turn-taking:\n"
                "   - The Judge asking 'Can I see the prayer?' or 'Can I see the order?' must be a separate speaker turn from Counsel answering 'Sir?' or 'Yes, My Lord'.\n"
                "   - Split merged turns into distinct, accurate speaker paragraphs whenever dialogue switches.\n"
                "   - CRITICAL SPEAKER RULE: You MUST ONLY use the allowed speaker tags listed above. DO NOT invent, create, or introduce any new speaker tags (such as SPEAKER_03, SPEAKER_04, etc.). Every single segment in your output MUST use one of the original allowed speaker tags.\n"
                "3. CONSOLIDATE OVER-SEGMENTED SPEAKERS & DETECT REAL HUMAN COUNT:\n"
                "   - Acoustic models frequently over-segment audio, creating 3 or 4 speaker tags when only 2 human speakers exist (e.g. assigning both SPEAKER_00 and SPEAKER_01 to Counsel addressing 'My Lord').\n"
                "   - Analyze legal honorifics ('My Lord', 'Your Honor', 'Sir?'), questions, and answers to determine the actual human speakers.\n"
                "   - Consolidate all turns uttered by the same human participant into a single speaker tag (e.g. SPEAKER_00 for Counsel, SPEAKER_01 for the Judge).\n"
                "4. Preserve the exact order and timing intervals as provided.\n\n"
                "Return ONLY a valid JSON object with a single top-level key 'realigned_segments':\n"
                "{\n"
                "  \"realigned_segments\": [\n"
                "    { \"speaker\": \"SPEAKER_00\", \"text\": \"...\", \"start\": 0.0, \"end\": 3.7 },\n"
                "    { \"speaker\": \"SPEAKER_01\", \"text\": \"...\", \"start\": 5.38, \"end\": 7.18 }\n"
                "  ]\n"
                "}"
            )

            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }

            body = {
                "model": self.model,
                "response_format": {"type": "json_object"},
                "temperature": 0.1,
                "messages": [
                    {"role": "system", "content": prompt_system},
                    {"role": "user", "content": json.dumps({"raw_segments": simplified_input})}
                ]
            }

            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=body,
                timeout=60
            )

            if response.status_code != 200:
                logger.error(f"OpenAI API call failed with status {response.status_code}: {response.text}")
                return segments

            result_json = response.json()
            content = result_json["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            realigned_segments = parsed.get("realigned_segments", [])

            if not realigned_segments:
                logger.warning("LLM returned empty realigned segments. Using original segments.")
                return segments

            logger.info(f"LLM Realignment pass completed: returned {len(realigned_segments)} realigned segments.")

            # Map realigned text and speaker tags back into segment structures with strict speaker tag enforcement
            final_segments = []
            allowed_set = set(existing_speakers)
            last_valid_speaker = existing_speakers[0] if existing_speakers else "SPEAKER_00"

            for seg in realigned_segments:
                spk = seg.get("speaker", "SPEAKER_00")
                if spk not in allowed_set:
                    logger.warning(f"LLM returned unauthorized speaker tag '{spk}' (allowed: {allowed_set}). Remapping to '{last_valid_speaker}'.")
                    spk = last_valid_speaker
                else:
                    last_valid_speaker = spk

                txt = seg.get("text", "")
                st = seg.get("start", 0.0)
                et = seg.get("end", 0.0)

                # Split words
                raw_words = txt.split()
                duration = max(0.1, et - st)
                step = duration / max(1, len(raw_words))

                words_list = []
                for idx, w_txt in enumerate(raw_words):
                    words_list.append({
                        "word": w_txt,
                        "start": round(st + (idx * step), 3),
                        "end": round(st + ((idx + 1) * step), 3),
                        "speaker": spk
                    })

                final_segments.append({
                    "start": st,
                    "end": et,
                    "text": txt,
                    "speaker": spk,
                    "words": words_list
                })

            return final_segments

        except Exception as e:
            logger.error(f"Error during LLM Realignment pass: {e}")
            return segments
