import os
import json
import logging
import requests
from typing import List, Dict, Any, Optional
from ml_worker.config import WorkerConfig

logger = logging.getLogger("ml_worker.llm_diarizer")

class LLMRealignmentEngine:
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY", "")
        self.model = os.getenv("OPENAI_MODEL", "gpt-4o")
        self.enabled = os.getenv("ENABLE_LLM_DIARIZATION", "true").lower() in ("true", "1", "yes")

    def process(self, segments: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Runs Layer 3 LLM Post-Processing on segments:
        1. Fixes acoustic legal homophone errors ("six d" -> "Order 8 Rule 6(d)", "call pleases" -> "As the Court pleases").
        2. Re-aligns speaker turn boundaries based on natural courtroom turn-taking and dialogue flow.
        """
        if not self.enabled or not self.api_key:
            logger.info("LLM Realignment disabled or OPENAI_API_KEY not configured. Skipping Layer 3 pass.")
            return segments

        if not segments:
            return segments

        try:
            logger.info(f"Running Layer 3 LLM Realignment pass on {len(segments)} segments using {self.model}...")

            # Prepare simplified input payload for LLM
            simplified_input = []
            for seg in segments:
                simplified_input.append({
                    "speaker": seg.get("speaker", "SPEAKER_00"),
                    "text": seg.get("text", "").strip(),
                    "start": seg.get("start"),
                    "end": seg.get("end")
                })

            # Extract set of original allowed speakers
            existing_speakers = sorted(list(set(seg.get("speaker", "SPEAKER_00") for seg in segments)))
            speaker_str = ", ".join(existing_speakers)

            prompt_system = (
                "You are an expert Courtroom Stenographer AI. You receive a raw transcript generated by acoustic speech models.\n"
                "Your job is to produce a pristine, highly accurate courtroom transcript with perfect legal text formatting, numeric digits, native name corrections, and accurate speaker turn attribution.\n\n"
                f"ALLOWED SPEAKER TAGS FROM ACOUSTIC DIARIZER: [{speaker_str}]\n\n"
                "GENERAL FORMATTING RULES FOR ALL AUDIOS:\n"
                "1. NUMBERS AS DIGITS (MANDATORY):\n"
                "   - ALL numbers spoken in the audio MUST be formatted as numeric digits (e.g. '8', '6', '1904', '2019', '14', '3', '1st') rather than spelled-out words ('eight', 'six', 'nineteen hundred', 'fourteen', 'three', 'first').\n"
                "   - Legal provisions: 'Order eight rule six d' -> 'Order 8 Rule 6(d)'.\n\n"
                "2. UNIVERSAL SUIT & CASE NUMBER FORMATTING (ANY SUIT NUMBER):\n"
                "   - Automatically detect and format ALL suit/case numbers called in ANY audio, regardless of letters, acronyms, or numbers.\n"
                "   - Convert spelled-out letters ('F H C', 'A B J', 'C A', 'N I C N', 'F A C', 'L A', 'C S') and spelled-out number series ('one nine zero four' -> '1904', 'twenty nineteen' -> '2019', 'fifty two' -> '52') into standard uppercase slashed suit citations (e.g., 'Suit No. FHC/L/CS/1904/2019', 'Suit No. ABJ/CR/52/2023', 'Suit No. CA/L/102/2021').\n"
                "   - Reconstruct suit numbers even if split across adjacent raw segments.\n\n"
                "3. CROSS-SEGMENT LEGAL HOMOPHONE & TERMINOLOGY CORRECTION:\n"
                "   - Correct acoustic homophones and misheard legal phrasing:\n"
                "     * 'call pleases' / 'call places' / 'as you call pleases' -> 'As the Court pleases'\n"
                "     * 'frontiered' / 'front-ended' -> 'front-loaded'\n"
                "     * 'emotional notice' / 'motion and notice' -> 'Motion on Notice'\n"
                "     * 'right of summons' -> 'Writ of Summons'\n"
                "     * 'my lord' -> 'My Lord', 'your honor' -> 'Your Honor'\n"
                "   - Capitalize legal titles, honorifics, and court documents properly.\n\n"
                "4. GENERAL CORRECTION OF NATIVE & AFRICAN PROPER NAMES:\n"
                "   - Speech models frequently mishear African/Nigerian proper names (people, judges, counsel, locations, legal entities).\n"
                "   - Recognize phonetic misspellings of native names from context and correct them to standard, proper native orthography (e.g. 'Kamolafe' -> 'Komolafe', 'Seydoux' / 'Seyidu' -> 'Saidu', 'Okonkwo', 'Adeyemi', 'Babajide', 'Chukwuma', 'Igwe', 'Danjuma').\n"
                "   - Capitalize all proper names and surnames appropriately.\n\n"
                "5. DYNAMIC SPEAKER ATTRIBUTION (MATCH ACTUAL HUMAN VOICES IN AUDIO):\n"
                "   - Determine the TRUE number of distinct human participants in the recording based on speech turns, legal roles (Plaintiff Counsel, Defendant Counsel, Judge, Witness), and dialogue continuity.\n"
                "   - Consolidate over-segmented acoustic fragments so that each distinct human speaker gets a single consistent speaker tag (e.g. if 2 people speak in the audio, output exactly 2 speaker tags; if 3 people speak, output 3 tags).\n"
                "   - DO NOT invent new speaker tags outside the allowed list. Use the minimum required allowed tags to represent the actual speakers.\n\n"
                "6. MERGE CONTINUOUS SENTENCES & FIX TIMINGS:\n"
                "   - Merge continuous raw segments belonging to the same sentence or speaker turn to form clean, natural paragraphs.\n"
                "   - Set the 'start' timestamp to the beginning of the first merged segment and 'end' timestamp to the end of the last merged segment.\n\n"
                "Return ONLY a valid JSON object with a single top-level key 'realigned_segments':\n"
                "{\n"
                "  \"realigned_segments\": [\n"
                "    { \"speaker\": \"SPEAKER_00\", \"text\": \"My Lord is giving me a new name.\", \"start\": 0.0, \"end\": 3.72 },\n"
                "    { \"speaker\": \"SPEAKER_01\", \"text\": \"Well, choose the one you want.\", \"start\": 5.38, \"end\": 7.18 }\n"
                "  ]\n"
                "}"
            )

            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }

            body = {
                "model": self.model,
                "response_format": {"type": "json_object"},
                "temperature": 0.1,
                "messages": [
                    {"role": "system", "content": prompt_system},
                    {"role": "user", "content": json.dumps({"raw_segments": simplified_input})}
                ]
            }

            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=body,
                timeout=60
            )

            if response.status_code != 200:
                logger.error(f"OpenAI API call failed with status {response.status_code}: {response.text}")
                return segments

            result_json = response.json()
            content = result_json["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            realigned_segments = parsed.get("realigned_segments", [])

            if not realigned_segments:
                logger.warning("LLM returned empty realigned segments. Using original segments.")
                return segments

            logger.info(f"LLM Realignment pass completed: returned {len(realigned_segments)} realigned segments.")

            # Map realigned text and speaker tags back into segment structures with strict speaker tag enforcement
            final_segments = []
            allowed_set = set(existing_speakers)
            last_valid_speaker = existing_speakers[0] if existing_speakers else "SPEAKER_00"

            for seg in realigned_segments:
                spk = seg.get("speaker", "SPEAKER_00")
                if spk not in allowed_set:
                    logger.warning(f"LLM returned unauthorized speaker tag '{spk}' (allowed: {allowed_set}). Remapping to '{last_valid_speaker}'.")
                    spk = last_valid_speaker
                else:
                    last_valid_speaker = spk

                txt = seg.get("text", "")
                st = seg.get("start", 0.0)
                et = seg.get("end", 0.0)

                # Split words
                raw_words = txt.split()
                duration = max(0.1, et - st)
                step = duration / max(1, len(raw_words))

                words_list = []
                for idx, w_txt in enumerate(raw_words):
                    words_list.append({
                        "word": w_txt,
                        "start": round(st + (idx * step), 3),
                        "end": round(st + ((idx + 1) * step), 3),
                        "speaker": spk
                    })

                final_segments.append({
                    "start": st,
                    "end": et,
                    "text": txt,
                    "speaker": spk,
                    "words": words_list
                })

            return final_segments

        except Exception as e:
            logger.error(f"Error during LLM Realignment pass: {e}")
            return segments
